var NSST_Tables = {
    ExplainType : [
        "正常發展",        // 0
        "進一步語言診斷",  // 1
        "介入語言教學"     // 2
    ],
    Acceptance_1 : [
        {score:  0, percentile: "1-", explain_type: 2},
        {score:  1, percentile: "1-", explain_type: 2},
        {score:  2, percentile: "1-", explain_type: 2},
        {score:  3, percentile: "1-", explain_type: 2},
        {score:  4, percentile: "1-", explain_type: 2},
        {score:  5, percentile: "1-", explain_type: 2},
        {score:  6, percentile: "1-", explain_type: 2},
        {score:  7, percentile: "1-", explain_type: 2},
        {score:  8, percentile: "1-", explain_type: 2},
        {score:  9, percentile: "1-", explain_type: 2},
        {score: 10, percentile: "1-", explain_type: 2},
        {score: 11, percentile: "1-", explain_type: 2},
        {score: 12, percentile: "1-", explain_type: 2},
        {score: 13, percentile: "1-", explain_type: 2},
        {score: 14, percentile: "1-", explain_type: 2},
        {score: 15, percentile: "1-", explain_type: 2},
        {score: 16, percentile: "1-", explain_type: 2},
        {score: 17, percentile: "1-", explain_type: 2},
        {score: 18, percentile: "1-", explain_type: 2},
        {score: 19, percentile: "1-", explain_type: 2},
        {score: 20, percentile: "1-", explain_type: 2},
        {score: 21, percentile: "1-", explain_type: 2},
        {score: 22, percentile: "1-", explain_type: 2},
        {score: 23, percentile: " 1", explain_type: 2},
        {score: 24, percentile: " 1", explain_type: 2},
        {score: 25, percentile: " 1", explain_type: 2},
        {score: 26, percentile: " 2", explain_type: 2},
        {score: 27, percentile: " 3", explain_type: 1},
        {score: 28, percentile: " 5", explain_type: 1},
        {score: 29, percentile: " 8", explain_type: 1},
        {score: 30, percentile: "13", explain_type: 0},
        {score: 31, percentile: "20", explain_type: 0},
        {score: 32, percentile: "26", explain_type: 0},
        {score: 33, percentile: "36", explain_type: 0},
        {score: 34, percentile: "49", explain_type: 0},
        {score: 35, percentile: "61", explain_type: 0},
        {score: 36, percentile: "73", explain_type: 0},
        {score: 37, percentile: "83", explain_type: 0},
        {score: 38, percentile: "92", explain_type: 0},
        {score: 39, percentile: "96", explain_type: 0},
        {score: 40, percentile: "99", explain_type: 0}
    ],
    Acceptance_2 : [
        {score:  0, percentile: "1-", explain_type: 2},
        {score:  1, percentile: "1-", explain_type: 2},
        {score:  2, percentile: "1-", explain_type: 2},
        {score:  3, percentile: "1-", explain_type: 2},
        {score:  4, percentile: "1-", explain_type: 2},
        {score:  5, percentile: "1-", explain_type: 2},
        {score:  6, percentile: "1-", explain_type: 2},
        {score:  7, percentile: "1-", explain_type: 2},
        {score:  8, percentile: "1-", explain_type: 2},
        {score:  9, percentile: "1-", explain_type: 2},
        {score: 10, percentile: "1-", explain_type: 2},
        {score: 11, percentile: "1-", explain_type: 2},
        {score: 12, percentile: "1-", explain_type: 2},
        {score: 13, percentile: "1-", explain_type: 2},
        {score: 14, percentile: "1-", explain_type: 2},
        {score: 15, percentile: "1-", explain_type: 2},
        {score: 16, percentile: "1-", explain_type: 2},
        {score: 17, percentile: "1-", explain_type: 2},
        {score: 18, percentile: "1-", explain_type: 2},
        {score: 19, percentile: "1-", explain_type: 2},
        {score: 20, percentile: "1-", explain_type: 2},
        {score: 21, percentile: "1-", explain_type: 2},
        {score: 22, percentile: "1-", explain_type: 2},
        {score: 23, percentile: "1-", explain_type: 2},
        {score: 24, percentile: "1-", explain_type: 2},
        {score: 25, percentile: " 1", explain_type: 2},
        {score: 26, percentile: " 1", explain_type: 2},
        {score: 27, percentile: " 1", explain_type: 2},
        {score: 28, percentile: " 1", explain_type: 2},
        {score: 29, percentile: " 3", explain_type: 1},
        {score: 30, percentile: " 6", explain_type: 1},
        {score: 31, percentile: "10", explain_type: 0},
        {score: 32, percentile: "15", explain_type: 0},
        {score: 33, percentile: "20", explain_type: 0},
        {score: 34, percentile: "27", explain_type: 0},
        {score: 35, percentile: "36", explain_type: 0},
        {score: 36, percentile: "51", explain_type: 0},
        {score: 37, percentile: "67", explain_type: 0},
        {score: 38, percentile: "78", explain_type: 0},
        {score: 39, percentile: "88", explain_type: 0},
        {score: 40, percentile: "97", explain_type: 0}
    ],
    Expressive_1 : [
        {score:  0, percentile: "1-", explain_type: 2},
        {score:  1, percentile: "1-", explain_type: 2},
        {score:  2, percentile: "1-", explain_type: 2},
        {score:  3, percentile: "1-", explain_type: 2},
        {score:  4, percentile: "1-", explain_type: 2},
        {score:  5, percentile: "1-", explain_type: 2},
        {score:  6, percentile: "1-", explain_type: 2},
        {score:  7, percentile: "1-", explain_type: 2},
        {score:  8, percentile: "1-", explain_type: 2},
        {score:  9, percentile: "1-", explain_type: 2},
        {score: 10, percentile: "1-", explain_type: 2},
        {score: 11, percentile: "1-", explain_type: 2},
        {score: 12, percentile: "1-", explain_type: 2},
        {score: 13, percentile: "1-", explain_type: 2},
        {score: 14, percentile: "1-", explain_type: 2},
        {score: 15, percentile: "1-", explain_type: 2},
        {score: 16, percentile: "1-", explain_type: 2},
        {score: 17, percentile: "1-", explain_type: 2},
        {score: 18, percentile: "1-", explain_type: 2},
        {score: 19, percentile: "1-", explain_type: 2},
        {score: 20, percentile: "1-", explain_type: 2},
        {score: 21, percentile: "1-", explain_type: 2},
        {score: 22, percentile: " 1", explain_type: 2},
        {score: 23, percentile: " 1", explain_type: 2},
        {score: 24, percentile: " 1", explain_type: 2},
        {score: 25, percentile: " 1", explain_type: 2},
        {score: 26, percentile: " 1", explain_type: 2},
        {score: 27, percentile: " 2", explain_type: 2},
        {score: 28, percentile: " 3", explain_type: 1},
        {score: 29, percentile: " 3", explain_type: 1},
        {score: 30, percentile: " 3", explain_type: 1},
        {score: 31, percentile: " 4", explain_type: 1},
        {score: 32, percentile: " 5", explain_type: 1},
        {score: 33, percentile: " 8", explain_type: 1},
        {score: 34, percentile: "12", explain_type: 0},
        {score: 35, percentile: "19", explain_type: 0},
        {score: 36, percentile: "31", explain_type: 0},
        {score: 37, percentile: "46", explain_type: 0},
        {score: 38, percentile: "62", explain_type: 0},
        {score: 39, percentile: "80", explain_type: 0},
        {score: 40, percentile: "94", explain_type: 0}
    ],
    Expressive_2 : [
        {score:  0, percentile: "1-", explain_type: 2},
        {score:  1, percentile: "1-", explain_type: 2},
        {score:  2, percentile: "1-", explain_type: 2},
        {score:  3, percentile: "1-", explain_type: 2},
        {score:  4, percentile: "1-", explain_type: 2},
        {score:  5, percentile: "1-", explain_type: 2},
        {score:  6, percentile: "1-", explain_type: 2},
        {score:  7, percentile: "1-", explain_type: 2},
        {score:  8, percentile: "1-", explain_type: 2},
        {score:  9, percentile: "1-", explain_type: 2},
        {score: 10, percentile: "1-", explain_type: 2},
        {score: 11, percentile: "1-", explain_type: 2},
        {score: 12, percentile: "1-", explain_type: 2},
        {score: 13, percentile: "1-", explain_type: 2},
        {score: 14, percentile: "1-", explain_type: 2},
        {score: 15, percentile: "1-", explain_type: 2},
        {score: 16, percentile: "1-", explain_type: 2},
        {score: 17, percentile: "1-", explain_type: 2},
        {score: 18, percentile: "1-", explain_type: 2},
        {score: 19, percentile: "1-", explain_type: 2},
        {score: 20, percentile: "1-", explain_type: 2},
        {score: 21, percentile: "1-", explain_type: 2},
        {score: 22, percentile: "1-", explain_type: 2},
        {score: 23, percentile: "1-", explain_type: 2},
        {score: 24, percentile: "1-", explain_type: 2},
        {score: 25, percentile: "1-", explain_type: 2},
        {score: 26, percentile: "1-", explain_type: 2},
        {score: 27, percentile: " 1", explain_type: 2},
        {score: 28, percentile: " 1", explain_type: 2},
        {score: 29, percentile: " 1", explain_type: 2},
        {score: 30, percentile: " 1", explain_type: 2},
        {score: 31, percentile: " 1", explain_type: 2},
        {score: 32, percentile: " 1", explain_type: 2},
        {score: 33, percentile: " 2", explain_type: 2},
        {score: 34, percentile: " 4", explain_type: 1},
        {score: 35, percentile: " 8", explain_type: 1},
        {score: 36, percentile: "15", explain_type: 0},
        {score: 37, percentile: "24", explain_type: 0},
        {score: 38, percentile: "38", explain_type: 0},
        {score: 39, percentile: "58", explain_type: 0},
        {score: 40, percentile: "85", explain_type: 0}
    ]
};

function NSST_Scoring(type, grade, score){
    var objTable = [];
    if(type == "Acceptance" && grade == 1) objTable = NSST_Tables.Acceptance_1;
    if(type == "Acceptance" && grade == 2) objTable = NSST_Tables.Acceptance_2;
    if(type == "Expressive" && grade == 1) objTable = NSST_Tables.Expressive_1;
    if(type == "Expressive" && grade == 2) objTable = NSST_Tables.Expressive_2;
    
    for(var i = 0; i < objTable.length; i++){
        if(score == objTable[i].score){
            return {
                percentile: objTable[i].percentile,
                explain: NSST_Tables.ExplainType[objTable[i].explain_type]
            };
        }
    }
    
    return {
        percentile: "n/a",
        explain: "n/a"
    };
}
